### ISSUE TITLE
Was ist mit "externen Listen" gemeint?

### ISSUE THREAD

**Issue by donni106** [konstin/oparl-validator-rs#1]
Hallo @konstin, danke für dein Tool! Ich erhalte Meldungen, die ich nicht wirklich verstehe:

> Das Objekt von Typ AgendaItem wurde von einem anderen Objekt verlinkt, fehlt aber in den externen Listen
> Das Objekt von Typ Consultation wurde von einem anderen Objekt verlinkt, fehlt aber in den externen Listen
> Das Objekt von Typ Location wurde von einem anderen Objekt verlinkt, fehlt aber in den externen Listen
> Das Objekt von Typ Meeting wurde von einem anderen Objekt verlinkt, fehlt aber in den externen Listen

Was ist denn jeweils mit "externen Listen" gemeint?

**Comment by konstin** [comment]
Das sind die Listen die in der Spezifikation als "Externe Objektlisten" beschrieben sind (https://oparl.org/spezifikation/online-ansicht/#objektlisten-und-paginierung). Alle Objekte vom Typ `Meeting` müssen zB in der Liste von `meeting` des jeweiligen `Body` verlinkt sein.

**Comment by donni106** [comment]
Danke, ich interpretiere folgendes, undzwar dass bei

```
{
      "id": ".../oparl/organization/Vergabe",
      "type": "https://schema.oparl.org/1.0/Organization",
      "body": ".../oparl/body/1",
      "name": "Vergabekommission",
      "membership": [
        ".../oparl/membership/Vergabe.259",
        ".../oparl/membership/Vergabe.405",
        ".../oparl/membership/Vergabe.50"
      ],
      "meeting": ".../oparl/organization/Vergabe/meeting",
      "shortName": "Vergabe",
      "organizationType": "Gremium"
    }
```

`meeting` auch ein Array sein müsste mit dem einen Eintrag, oder?

**Comment by konstin** [comment]
Nein, `meeting` ist eine url. Die url wiederum gibt eine Liste von Objekten vom typ `Meeting` zurück. Die Liste muss alle `Meeting`s haben, die zur jeweiligen `Organization` gehören (also sowas wie `SELECT * FROM meetings WHERE meeting.organization._id == <organization.id>` mit entsprechendem `LIMIT` und `meeting .id > <last_id>` für die Paginierung)

**Comment by donni106** [comment]
Hm, ok unter `.../oparl/organization/Vergabe/meeting` gibt es ganz viele Einträge mit jeweils:

```
...
"organization": [
  ".../oparl/organization/Vergabe"
],
...
```

So weit so richtig, oder? Hier allerdings auch der eine Eintrag als Array in `organization` und nicht als String.

**Comment by konstin** [comment]
Im eigentlichen Log sollten sich mehr Details finden, u.a. die id die fehlt: In der `meeting`-Liste des Bodies sollten alle ids der Meetings zu finden sein, aber das angebene Meeting fehlt.

**Comment by donni106** [comment]
Die Detaillogs sagen alle nur sowas, in "unserem" Fall hier:

> .../oparl/organization/Vergabe/meeting verlinkt von .../oparl/organization/Vergabe und 0 anderen

In anderen Fällen sind es untersch. Anzahlen von "anderen". Was kann ich damit anfangen?

**Comment by konstin** [comment]
Das ist ohne die tatsächlichen urls und json files zu sehen leider schwer zu sagen. `.../oparl/organization/Vergabe` verlinkt ein Objekt mit der id `.../oparl/organization/Vergabe/meeting`, dieses ist aber nicht in der externen Liste die alle Meetings des Bodies enthalten sollte drinnen. `--report` schreibt eine Datei mit jedem der einzelnen Fälle.

**Comment by donni106** [comment]
`--report foo.txt` unterscheidet sich im Output augenscheinlich nicht von der sonst auch exportierten `report.txt`.
Ok, danke dir soweit sehr. Ich gebe ein paar Informationen weiter und hoffe, dass diese den entsprechenden Kollegen helfen werden.
